export const COLD_CALL_STATUS_LABELS: Record<string, string> = {
  not_contacted: "Not yet called",
  called: "Called, not yet emailed",
  emailed: "Follow-up emailed",
  meeting_booked: "Meeting booked",
  contacted: "Email sent",
  followup_1_sent: "Follow-up 1 sent",
  followup_2_sent: "Follow-up 2 sent",
  followup_3_sent: "Follow-up 3 sent",
  followup_4_sent: "Follow-up 4 sent",
  replied: "Replied",
  booked: "Booked",
  no_show: "No Show",
  rebooked: "Rebooked",
  proposal_sent: "Proposal Sent",
  closed: "Closed",
  no_close: "No Close",
  thinking_about_it: "Thinking About It",
  not_interested: "Not interested",
  bounced: "Bounced",
  sequence_complete: "Sequence complete",
  discovery_done: "Discovery Done",
  onboarding: "Onboarding",
  ready_to_launch: "Ready to Launch",
};

export const COLD_CALL_STATUS_COLORS: Record<string, { bg: string; text: string }> = {
  meeting_booked: { bg: "#dcfce7", text: "#166534" },
  booked: { bg: "#dcfce7", text: "#166534" },
  emailed: { bg: "#dbeafe", text: "#1e40af" },
  replied: { bg: "#dbeafe", text: "#1e40af" },
  no_show: { bg: "#fef3c7", text: "#92400e" },
  rebooked: { bg: "#d1fae5", text: "#065f46" },
  proposal_sent: { bg: "#ede9fe", text: "#5b21b6" },
  not_interested: { bg: "#fee2e2", text: "#991b1b" },
  bounced: { bg: "#fee2e2", text: "#991b1b" },
  closed: { bg: "#dcfce7", text: "#14532d" },
  no_close: { bg: "#fee2e2", text: "#991b1b" },
  thinking_about_it: { bg: "#fef9c3", text: "#854d0e" },
  discovery_done: { bg: "#dbeafe", text: "#1e40af" },
  onboarding: { bg: "#e0e7ff", text: "#3730a3" },
  ready_to_launch: { bg: "#dcfce7", text: "#166534" },
};
